### ISSUE TITLE
Manifest V.3

### ISSUE THREAD

**Issue by HuggeK** [luddd3/veckonr#2]
What will happen in January? Have tried adopting it but have failed repetitively, I really don´t know Javascript, yet. 
[](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/ )

**Comment by luddd3** [comment]
I don't really know. I haven't done any development on this extension for 7 years and haven't been using it for a while either...

Edit:
I see now that you did a pull request as well. I'm sorry, but I don't have any time to help you. Maybe ask on Stackoverflow?

**Comment by luddd3** [comment]
I marked my repo as deprecated and referred all future visitors to your repo =)

**Comment by HuggeK** [comment]
Thank you, got manifest v3 to work in my experimental branch - but sacrificed the theme detection part.
